## read data from files

In [1]:
import os
import wget
if os.path.isfile("utilsLaris.py")==True:
    os. remove("utilsLaris.py")
wget.download("https://raw.githubusercontent.com/Ah-essabar/LARIS01/master/utilsLaris.py")

import janitor
import os
import glob
#import mitosheet
import ipywidgets as widgets
%matplotlib inline
#%matplotlib widget
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns
import utilsLaris

from pylab import rcParams
import matplotlib.pyplot as plt
from matplotlib import rc
from pandas.plotting import register_matplotlib_converters

from sklearn.model_selection import cross_val_score


%config InlineBackend.figure_format='retina'

register_matplotlib_converters()
sns.set(style='whitegrid', palette='muted', font_scale=1.5)

rcParams['figure.figsize'] = 22, 10

RANDOM_SEED = 42

In [2]:
#!pip install sklearn

In [3]:
import pandas as pd
p=0.50
X=pd.read_csv("X_219_25mai.csv", parse_dates=["date"], index_col="date")
y=pd.read_csv("y_219_25mai.csv", parse_dates=["date"], index_col="date")

# X=pd.read_csv("X_219_31mai.csv", parse_dates=["date"], index_col="date")
# y=pd.read_csv("y_219_31mai.csv", parse_dates=["date"], index_col="date")
#y = y.values.ravel()
# X_train = X[:int(X.shape[0]*p)]
# X_test = X[int(X.shape[0]*p):]
# y_train = y[:int(X.shape[0]*p)]
# y_test = y[int(X.shape[0]*p):]
# X_train.shape

In [4]:
X

,co2_100,tvoc_100,temperature_100,humidity_100,light_100,sound_100,co2_101,tvoc_101,temperature_101,humidity_101,...,tvoc_112,temperature_112,humidity_112,light_112,sound_112,weather_out,weather_hum,weather_bar_,weather_rad_,windows
date,,,,,,,,,,,,,,,,,,,,,
2022-03-25 16:45:00,431.000000,101.750000,24.277500,18.717500,1023.000000,509.500000,307.000000,51.750000,21.862500,20.172500,...,125.500000,26.9500,16.100000,464.000000,511.000000,21.200000,22.500000,1023.900000,344.500000,3
2022-03-25 16:50:00,479.000000,119.333333,24.486667,18.933333,1022.000000,510.000000,308.000000,65.000000,22.256667,19.870000,...,127.333333,26.9900,16.093333,458.666667,511.666667,21.166667,22.666667,1023.900000,333.000000,0
2022-03-25 16:55:00,401.666667,88.000000,23.396667,19.770000,1023.000000,509.666667,355.666667,102.333333,23.266667,19.556667,...,127.000000,26.7525,16.335000,433.000000,510.500000,21.133333,22.833333,1023.900000,321.500000,0
2022-03-25 17:00:00,435.500000,183.000000,25.515000,17.945000,1022.750000,509.500000,338.750000,197.250000,25.135000,18.025000,...,154.000000,27.1100,16.292500,406.000000,511.000000,21.100000,23.000000,1023.900000,310.000000,0
2022-03-25 17:05:00,431.333333,230.666667,26.533333,17.183333,1022.666667,509.000000,337.333333,234.333333,26.130000,17.266667,...,201.500000,27.4000,16.302500,399.750000,512.250000,21.033333,23.666667,1023.916667,297.166667,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-05-03 23:35:00,412.600000,1079.800000,24.780000,30.770000,316.600000,509.600000,411.200000,1004.800000,24.684000,30.682000,...,778.800000,24.8960,30.314000,0.000000,511.000000,14.100000,66.000000,1020.100000,0.000000,0
2022-05-03 23:40:00,410.250000,1072.000000,24.770000,30.780000,340.500000,509.250000,410.750000,1002.250000,24.697500,30.697500,...,768.500000,24.9075,30.295000,0.000000,511.000000,14.100000,66.000000,1020.100000,0.000000,0
2022-05-03 23:45:00,413.750000,1061.000000,24.782500,30.762500,324.750000,509.500000,411.250000,989.250000,24.665000,30.722500,...,752.000000,24.9000,30.290000,0.000000,511.200000,14.000000,66.000000,1020.100000,0.000000,0
2022-05-03 23:50:00,415.250000,1049.750000,24.757500,30.830000,331.000000,509.750000,409.000000,982.750000,24.660000,30.772500,...,754.000000,24.8980,30.356000,0.000000,511.200000,13.900000,66.000000,1020.100000,0.000000,0
2022-05-03 23:55:00,414.800000,1044.800000,24.752000,30.908000,333.600000,509.800000,406.200000,971.800000,24.658000,30.834000,...,745.000000,24.8860,30.446000,0.000000,511.000000,14.000000,66.000000,1020.200000,0.000000,0

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.35, shuffle=False)

In [8]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()
# RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
#                       max_depth=None, max_features='auto', max_leaf_nodes=None,
#                       max_samples=None, min_impurity_decrease=0.0,
#                       min_impurity_split=None, min_samples_leaf=1,
#                       min_samples_split=2, min_weight_fraction_leaf=0.0,
#                       n_estimators=100, n_jobs=None, oob_score=False,
#                       random_state=None, verbose=0, warm_start=False)

In [9]:
#y_train=y_train.values.ravel()
rfr.fit(X_train, y_train.values.ravel())
score = rfr.score(X_train, y_train.values.ravel())
print("R-squared:", score)

R-squared: 0.9879392941269248

In [10]:
from sklearn.metrics import mean_squared_error
y_pred = rfr.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred,squared=False)
print("MSE: ", mse)
print("RMSE: ", rmse)

MSE:  11525.83638034069
RMSE:  107.35844810885024

In [11]:
from sklearn.feature_selection import SelectFromModel
# rfr = clf.fit(xtrain, ytrain)
# clf.feature_importances_  
# array([ 0.04...,  0.05...,  0.4...,  0.4...])
model = SelectFromModel(rfr, prefit=True)
X_new = model.transform(X_train)
#X_new

In [12]:
X_train.loc[:,model.get_support()].columns

Index(['temperature_100', 'tvoc_101', 'temperature_101', 'sound_101',
       'co2_102', 'tvoc_103', 'co2_106', 'sound_108', 'temperature_111',
       'weather_out', 'weather_bar_'],
      dtype='object')

In [13]:
X_train.loc[:,model.get_support()]

,temperature_100,tvoc_101,temperature_101,sound_101,co2_102,tvoc_103,co2_106,sound_108,temperature_111,weather_out,weather_bar_
date,,,,,,,,,,,
2022-03-25 16:45:00,24.277500,51.750000,21.862500,537.250000,421.500000,27.666667,388.750000,11.0,27.492500,21.200000,1023.900000
2022-03-25 16:50:00,24.486667,65.000000,22.256667,553.000000,366.000000,50.500000,394.666667,11.0,27.536667,21.166667,1023.900000
2022-03-25 16:55:00,23.396667,102.333333,23.266667,504.666667,415.333333,123.666667,400.333333,11.0,27.430000,21.133333,1023.900000
2022-03-25 17:00:00,25.515000,197.250000,25.135000,471.750000,413.250000,171.666667,403.250000,11.0,27.650000,21.100000,1023.900000
2022-03-25 17:05:00,26.533333,234.333333,26.130000,509.666667,411.666667,201.250000,406.666667,11.0,27.817500,21.033333,1023.916667
...,...,...,...,...,...,...,...,...,...,...,...
2022-04-20 05:25:00,23.985000,342.750000,23.622500,178.500000,409.000000,225.750000,421.000000,3.6,24.276000,8.100000,1013.800000
2022-04-20 05:30:00,23.992500,344.000000,23.627500,202.250000,414.750000,223.500000,420.750000,3.2,24.292500,8.100000,1013.700000
2022-04-20 05:35:00,23.994000,346.800000,23.644000,261.400000,404.500000,228.750000,421.000000,3.0,24.278000,7.900000,1013.700000
2022-04-20 05:40:00,24.005000,346.500000,23.647500,173.750000,404.200000,230.200000,422.500000,3.4,24.294000,7.900000,1013.700000
2022-04-20 05:45:00,24.004000,354.000000,23.650000,198.250000,401.000000,229.750000,425.400000,3.6,24.308000,7.900000,1013.700000

In [15]:
rfrSelected = RandomForestRegressor()
rfrSelected.fit(X_train.loc[:,model.get_support()], y_train.values.ravel())
score = rfrSelected.score(X_train.loc[:,model.get_support()], y_train.values.ravel())
print("R-squared:", score)

R-squared: 0.9884027941945216

In [16]:
from sklearn.metrics import mean_squared_error
y_pred = rfrSelected.predict(X_test.loc[:,model.get_support()])
mse = mean_squared_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred,squared=False)
print("MSE: ", mse)
print("RMSE: ", rmse)

MSE:  14560.547509005828
RMSE:  120.66709372901059

In [17]:
X_trainS = X_train.loc[:,model.get_support()]
X_testS = X_test.loc[:,model.get_support()]

In [19]:
X_trainSF, y_trainF =utilsLaris.FeatureExtraction(X_trainS,y_train, period = '30T')
X_testSF, y_testF =utilsLaris.FeatureExtraction(X_testS,y_test, period = '30T')

In [20]:
X_testSF.shape

(661, 55)

In [23]:
rfrSelectedF = RandomForestRegressor()
rfrSelectedF.fit(X_trainSF, y_trainF.values.ravel())
score = rfrSelectedF.score(X_trainSF, y_trainF.values.ravel())
print("R-squared:", score)

R-squared: 0.9661151855841684

In [24]:
from sklearn.metrics import mean_squared_error
y_pred = rfrSelectedF.predict(X_testSF)
mse = mean_squared_error(y_testF, y_pred)
rmse = mean_squared_error(y_testF, y_pred,squared=False)
print("MSE: ", mse)
print("RMSE: ", rmse)

MSE:  5082.19929635279
RMSE:  71.28954549127656

In [25]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import Lasso

In [26]:
pipeline = Pipeline([
                     ('scaler',StandardScaler()),
                     ('model',Lasso())
])

In [33]:
search = GridSearchCV(pipeline,
                      {'model__alpha':np.arange(4,7,0.1)},
                      cv = 5, scoring="neg_mean_squared_error",verbose=3
                      )

In [34]:
import warnings
warnings.filterwarnings("ignore")
search.fit(X_train,y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits
[CV 1/5] END .............model__alpha=4.0;, score=-11645.061 total time=   0.0s
[CV 2/5] END .............model__alpha=4.0;, score=-14475.831 total time=   0.0s
[CV 3/5] END ..............model__alpha=4.0;, score=-9025.832 total time=   0.0s
[CV 4/5] END .............model__alpha=4.0;, score=-19380.189 total time=   0.0s
[CV 5/5] END .............model__alpha=4.0;, score=-22740.350 total time=   0.0s
[CV 1/5] END .............model__alpha=4.1;, score=-11631.320 total time=   0.0s
[CV 2/5] END .............model__alpha=4.1;, score=-14489.118 total time=   0.0s
[CV 3/5] END ..............model__alpha=4.1;, score=-8990.120 total time=   0.0s
[CV 4/5] END .............model__alpha=4.1;, score=-19371.067 total time=   0.0s
[CV 5/5] END .............model__alpha=4.1;, score=-22745.669 total time=   0.0s
[CV 1/5] END model__alpha=4.199999999999999;, score=-11618.772 total time=   0.0s
[CV 2/5] END model__alpha=4.199999999999999;, score=-14502.670 total time=   0.0s
[CV 3/5] END model__alpha=4.199999999999999;, score=-8955.927 total time=   0.0s
[CV 4/5] END model__alpha=4.199999999999999;, score=-19367.071 total time=   0.0s
[CV 5/5] END model__alpha=4.199999999999999;, score=-22751.115 total time=   0.0s
[CV 1/5] END model__alpha=4.299999999999999;, score=-11607.581 total time=   0.0s
[CV 2/5] END model__alpha=4.299999999999999;, score=-14516.583 total time=   0.0s
[CV 3/5] END model__alpha=4.299999999999999;, score=-8922.827 total time=   0.0s
[CV 4/5] END model__alpha=4.299999999999999;, score=-19363.723 total time=   0.0s
[CV 5/5] END model__alpha=4.299999999999999;, score=-22760.371 total time=   0.0s
[CV 1/5] END model__alpha=4.399999999999999;, score=-11597.700 total time=   0.0s
[CV 2/5] END model__alpha=4.399999999999999;, score=-14530.877 total time=   0.0s
[CV 3/5] END model__alpha=4.399999999999999;, score=-8890.795 total time=   0.0s
[CV 4/5] END model__alpha=4.399999999999999;, score=-19361.056 total time=   0.0s
[CV 5/5] END model__alpha=4.399999999999999;, score=-22770.921 total time=   0.0s
[CV 1/5] END model__alpha=4.499999999999998;, score=-11589.184 total time=   0.0s
[CV 2/5] END model__alpha=4.499999999999998;, score=-14545.559 total time=   0.0s
[CV 3/5] END model__alpha=4.499999999999998;, score=-8860.344 total time=   0.0s
[CV 4/5] END model__alpha=4.499999999999998;, score=-19359.093 total time=   0.0s
[CV 5/5] END model__alpha=4.499999999999998;, score=-22781.231 total time=   0.0s
[CV 1/5] END model__alpha=4.599999999999998;, score=-11581.952 total time=   0.0s
[CV 2/5] END model__alpha=4.599999999999998;, score=-14560.627 total time=   0.0s
[CV 3/5] END model__alpha=4.599999999999998;, score=-8831.207 total time=   0.0s
[CV 4/5] END model__alpha=4.599999999999998;, score=-19358.009 total time=   0.0s
[CV 5/5] END model__alpha=4.599999999999998;, score=-22791.598 total time=   0.0s
[CV 1/5] END model__alpha=4.6999999999999975;, score=-11576.069 total time=   0.0s
[CV 2/5] END model__alpha=4.6999999999999975;, score=-14576.083 total time=   0.0s
[CV 3/5] END model__alpha=4.6999999999999975;, score=-8803.610 total time=   0.0s
[CV 4/5] END model__alpha=4.6999999999999975;, score=-19357.838 total time=   0.0s
[CV 5/5] END model__alpha=4.6999999999999975;, score=-22802.021 total time=   0.0s
[CV 1/5] END model__alpha=4.799999999999997;, score=-11572.950 total time=   0.0s
[CV 2/5] END model__alpha=4.799999999999997;, score=-14591.934 total time=   0.0s
[CV 3/5] END model__alpha=4.799999999999997;, score=-8777.478 total time=   0.0s
[CV 4/5] END model__alpha=4.799999999999997;, score=-19357.590 total time=   0.0s
[CV 5/5] END model__alpha=4.799999999999997;, score=-22812.504 total time=   0.0s
[CV 1/5] END model__alpha=4.899999999999997;, score=-11560.893 total time=   0.0s
[CV 2/5] END model__alpha=4.899999999999997;, score=-14608.179 total time=   0.0s
[CV 3/5] END model__alpha=4.899999999999997;, score=-8752.914 total time=   0.0s
[CV 4/5] END model__alpha=4.899999999999997;, score=-19358.024 total time=   0.0s
[CV 5/5] END model__alpha=4.899999999999997;, score=-22823.053 total time=   0.0s
[CV 1/5] END model__alpha=4.9999999999999964;, score=-11548.019 total time=   0.0s
[CV 2/5] END model__alpha=4.9999999999999964;, score=-14624.815 total time=   0.0s
[CV 3/5] END model__alpha=4.9999999999999964;, score=-8729.591 total time=   0.0s
[CV 4/5] END model__alpha=4.9999999999999964;, score=-19359.366 total time=   0.0s
[CV 5/5] END model__alpha=4.9999999999999964;, score=-22833.656 total time=   0.0s
[CV 1/5] END model__alpha=5.099999999999996;, score=-11536.787 total time=   0.0s
[CV 2/5] END model__alpha=5.099999999999996;, score=-14640.388 total time=   0.0s
[CV 3/5] END model__alpha=5.099999999999996;, score=-8707.871 total time=   0.0s
[CV 4/5] END model__alpha=5.099999999999996;, score=-19362.793 total time=   0.0s
[CV 5/5] END model__alpha=5.099999999999996;, score=-22844.326 total time=   0.0s
[CV 1/5] END model__alpha=5.199999999999996;, score=-11527.128 total time=   0.0s
[CV 2/5] END model__alpha=5.199999999999996;, score=-14656.874 total time=   0.0s
[CV 3/5] END model__alpha=5.199999999999996;, score=-8687.723 total time=   0.0s
[CV 4/5] END model__alpha=5.199999999999996;, score=-19367.041 total time=   0.0s
[CV 5/5] END model__alpha=5.199999999999996;, score=-22855.050 total time=   0.0s
[CV 1/5] END model__alpha=5.299999999999995;, score=-11519.073 total time=   0.0s
[CV 2/5] END model__alpha=5.299999999999995;, score=-14673.742 total time=   0.0s
[CV 3/5] END model__alpha=5.299999999999995;, score=-8669.101 total time=   0.0s
[CV 4/5] END model__alpha=5.299999999999995;, score=-19371.698 total time=   0.0s
[CV 5/5] END model__alpha=5.299999999999995;, score=-22865.836 total time=   0.0s
[CV 1/5] END model__alpha=5.399999999999995;, score=-11512.648 total time=   0.0s
[CV 2/5] END model__alpha=5.399999999999995;, score=-14671.650 total time=   0.0s
[CV 3/5] END model__alpha=5.399999999999995;, score=-8645.621 total time=   0.0s
[CV 4/5] END model__alpha=5.399999999999995;, score=-19376.795 total time=   0.0s
[CV 5/5] END model__alpha=5.399999999999995;, score=-22876.681 total time=   0.0s
[CV 1/5] END model__alpha=5.499999999999995;, score=-11507.760 total time=   0.0s
[CV 2/5] END model__alpha=5.499999999999995;, score=-14643.447 total time=   0.0s
[CV 3/5] END model__alpha=5.499999999999995;, score=-8620.400 total time=   0.0s
[CV 4/5] END model__alpha=5.499999999999995;, score=-19382.481 total time=   0.0s
[CV 5/5] END model__alpha=5.499999999999995;, score=-22887.588 total time=   0.0s
[CV 1/5] END model__alpha=5.599999999999994;, score=-11504.263 total time=   0.0s
[CV 2/5] END model__alpha=5.599999999999994;, score=-14615.577 total time=   0.0s
[CV 3/5] END model__alpha=5.599999999999994;, score=-8596.702 total time=   0.0s
[CV 4/5] END model__alpha=5.599999999999994;, score=-19388.663 total time=   0.0s
[CV 5/5] END model__alpha=5.599999999999994;, score=-22898.556 total time=   0.0s
[CV 1/5] END model__alpha=5.699999999999994;, score=-11502.314 total time=   0.0s
[CV 2/5] END model__alpha=5.699999999999994;, score=-14587.957 total time=   0.0s
[CV 3/5] END model__alpha=5.699999999999994;, score=-8578.878 total time=   0.0s
[CV 4/5] END model__alpha=5.699999999999994;, score=-19395.420 total time=   0.0s
[CV 5/5] END model__alpha=5.699999999999994;, score=-22907.651 total time=   0.0s
[CV 1/5] END model__alpha=5.799999999999994;, score=-11502.425 total time=   0.0s
[CV 2/5] END model__alpha=5.799999999999994;, score=-14560.827 total time=   0.0s
[CV 3/5] END model__alpha=5.799999999999994;, score=-8564.052 total time=   0.0s
[CV 4/5] END model__alpha=5.799999999999994;, score=-19402.604 total time=   0.0s
[CV 5/5] END model__alpha=5.799999999999994;, score=-22915.825 total time=   0.0s
[CV 1/5] END model__alpha=5.899999999999993;, score=-11504.233 total time=   0.0s
[CV 2/5] END model__alpha=5.899999999999993;, score=-14534.173 total time=   0.0s
[CV 3/5] END model__alpha=5.899999999999993;, score=-8550.673 total time=   0.0s
[CV 4/5] END model__alpha=5.899999999999993;, score=-19410.299 total time=   0.0s
[CV 5/5] END model__alpha=5.899999999999993;, score=-22924.095 total time=   0.0s
[CV 1/5] END model__alpha=5.999999999999993;, score=-11507.758 total time=   0.0s
[CV 2/5] END model__alpha=5.999999999999993;, score=-14508.011 total time=   0.0s
[CV 3/5] END model__alpha=5.999999999999993;, score=-8538.592 total time=   0.0s
[CV 4/5] END model__alpha=5.999999999999993;, score=-19418.524 total time=   0.0s
[CV 5/5] END model__alpha=5.999999999999993;, score=-22932.794 total time=   0.0s
[CV 1/5] END model__alpha=6.0999999999999925;, score=-11512.925 total time=   0.0s
[CV 2/5] END model__alpha=6.0999999999999925;, score=-14483.425 total time=   0.0s
[CV 3/5] END model__alpha=6.0999999999999925;, score=-8527.768 total time=   0.0s
[CV 4/5] END model__alpha=6.0999999999999925;, score=-19427.217 total time=   0.0s
[CV 5/5] END model__alpha=6.0999999999999925;, score=-22941.566 total time=   0.0s
[CV 1/5] END model__alpha=6.199999999999992;, score=-11520.225 total time=   0.0s
[CV 2/5] END model__alpha=6.199999999999992;, score=-14459.998 total time=   0.0s
[CV 3/5] END model__alpha=6.199999999999992;, score=-8518.245 total time=   0.0s
[CV 4/5] END model__alpha=6.199999999999992;, score=-19436.380 total time=   0.0s
[CV 5/5] END model__alpha=6.199999999999992;, score=-22950.436 total time=   0.0s
[CV 1/5] END model__alpha=6.299999999999992;, score=-11528.635 total time=   0.0s
[CV 2/5] END model__alpha=6.299999999999992;, score=-14437.018 total time=   0.0s
[CV 3/5] END model__alpha=6.299999999999992;, score=-8510.060 total time=   0.0s
[CV 4/5] END model__alpha=6.299999999999992;, score=-19446.012 total time=   0.0s
[CV 5/5] END model__alpha=6.299999999999992;, score=-22959.301 total time=   0.0s
[CV 1/5] END model__alpha=6.3999999999999915;, score=-11538.666 total time=   0.0s
[CV 2/5] END model__alpha=6.3999999999999915;, score=-14414.484 total time=   0.0s
[CV 3/5] END model__alpha=6.3999999999999915;, score=-8503.252 total time=   0.0s
[CV 4/5] END model__alpha=6.3999999999999915;, score=-19456.109 total time=   0.0s
[CV 5/5] END model__alpha=6.3999999999999915;, score=-22968.070 total time=   0.0s
[CV 1/5] END model__alpha=6.499999999999991;, score=-11549.174 total time=   0.0s
[CV 2/5] END model__alpha=6.499999999999991;, score=-14392.393 total time=   0.0s
[CV 3/5] END model__alpha=6.499999999999991;, score=-8497.830 total time=   0.0s
[CV 4/5] END model__alpha=6.499999999999991;, score=-19469.449 total time=   0.0s
[CV 5/5] END model__alpha=6.499999999999991;, score=-22976.880 total time=   0.0s
[CV 1/5] END model__alpha=6.599999999999991;, score=-11560.083 total time=   0.0s
[CV 2/5] END model__alpha=6.599999999999991;, score=-14370.736 total time=   0.0s
[CV 3/5] END model__alpha=6.599999999999991;, score=-8494.663 total time=   0.0s
[CV 4/5] END model__alpha=6.599999999999991;, score=-19485.911 total time=   0.0s
[CV 5/5] END model__alpha=6.599999999999991;, score=-22985.744 total time=   0.0s
[CV 1/5] END model__alpha=6.69999999999999;, score=-11572.300 total time=   0.0s
[CV 2/5] END model__alpha=6.69999999999999;, score=-14349.527 total time=   0.0s
[CV 3/5] END .model__alpha=6.69999999999999;, score=-8492.984 total time=   0.0s
[CV 4/5] END model__alpha=6.69999999999999;, score=-19502.668 total time=   0.0s
[CV 5/5] END model__alpha=6.69999999999999;, score=-22994.529 total time=   0.0s
[CV 1/5] END model__alpha=6.79999999999999;, score=-11587.722 total time=   0.0s
[CV 2/5] END model__alpha=6.79999999999999;, score=-14328.750 total time=   0.0s
[CV 3/5] END .model__alpha=6.79999999999999;, score=-8492.658 total time=   0.0s
[CV 4/5] END model__alpha=6.79999999999999;, score=-19519.820 total time=   0.0s
[CV 5/5] END model__alpha=6.79999999999999;, score=-23003.363 total time=   0.0s
[CV 1/5] END model__alpha=6.89999999999999;, score=-11608.241 total time=   0.0s
[CV 2/5] END model__alpha=6.89999999999999;, score=-14313.048 total time=   0.0s
[CV 3/5] END .model__alpha=6.89999999999999;, score=-8493.677 total time=   0.0s
[CV 4/5] END model__alpha=6.89999999999999;, score=-19537.302 total time=   0.0s
[CV 5/5] END model__alpha=6.89999999999999;, score=-23012.275 total time=   0.0s

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model', Lasso())]),
             param_grid={'model__alpha': array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2,
       5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5,
       6.6, 6.7, 6.8, 6.9])},
             scoring='neg_mean_squared_error', verbose=3)

In [35]:
search.best_params_

{'model__alpha': 6.3999999999999915}

In [36]:
coefficients = search.best_estimator_.named_steps['model'].coef_

In [37]:
importance = np.abs(coefficients)

In [38]:
# importance

In [39]:
features = X_train.columns
np.array(features)[importance > 0]

array(['temperature_100', 'co2_102', 'tvoc_105', 'temperature_105',
       'humidity_105', 'temperature_106', 'temperature_110', 'co2_111',
       'light_111', 'tvoc_112', 'weather_out', 'windows'], dtype=object)

In [41]:
# X1 = X['temperature_100_max', 'temperature_105_max', 'co2_111_max',
#        'tvoc_106_std']

In [42]:
selectedFeatures = ['temperature_100_max', 'temperature_105_max', 'co2_111_max',
       'tvoc_106_std']
selectedFeatures = np.array(features)[importance > 0]
X_test_selected = X_test[selectedFeatures].copy()
X_train_selected = X_train[selectedFeatures].copy()

In [43]:
y_train

                     elecWithoutEclairage
date
2022-03-25 16:45:00               459.440
2022-03-25 16:50:00               402.204
2022-03-25 16:55:00               408.186
2022-03-25 17:00:00               452.432
2022-03-25 17:05:00               445.334
...                                   ...
2022-04-20 05:25:00               294.142
2022-04-20 05:30:00               303.908
2022-04-20 05:35:00               302.670
2022-04-20 05:40:00               303.260
2022-04-20 05:45:00               302.100

[7357 rows x 1 columns]

In [46]:
X_train_selected, y_train= utilsLaris.FeatureExtraction(X_train_selected,y_train, period = '30T')
X_test_selected, y_test=utilsLaris.FeatureExtraction(X_test_selected,y_test, period = '30T')

In [47]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()
RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

RandomForestRegressor()

In [48]:
rfr.fit(X_train_selected, y_train)
score = rfr.score(X_train_selected, y_train)
print("R-squared:", score)

R-squared: 0.9596077640642741

In [49]:
from sklearn.metrics import mean_squared_error
y_pred = rfr.predict(X_test_selected)
mse = mean_squared_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred,squared=False)
print("MSE: ", mse)
print("RMSE: ", rmse)

MSE:  4738.02979072297
RMSE:  68.83334795520969

In [ ]:
y_pred.max()

In [50]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from scipy import stats

X2 = sm.add_constant(X_train_selected)
est = sm.OLS(y_train, X2)
est2 = est.fit()
print(est2.summary())

                             OLS Regression Results
================================================================================
Dep. Variable:     elecWithoutEclairage   R-squared:                       0.624
Model:                              OLS   Adj. R-squared:                  0.608
Method:                   Least Squares   F-statistic:                     38.98
Date:                  Wed, 01 Jun 2022   Prob (F-statistic):          2.61e-212
Time:                          11:35:54   Log-Likelihood:                -7278.8
No. Observations:                  1227   AIC:                         1.466e+04
Df Residuals:                      1176   BIC:                         1.492e+04
Df Model:                            50
Covariance Type:              nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                -1110.8429    125.272     -8.867      0.000   -1356.624    -865.062
temperature_100_max    395.4104     83.543      4.733      0.000     231.501     559.320
co2_102_max             -0.3843      0.430     -0.895      0.371      -1.227       0.459
tvoc_105_max             0.0158      0.029      0.553      0.581      -0.040       0.072
temperature_105_max    225.8687    145.702      1.550      0.121     -59.997     511.734
humidity_105_max        25.7243     56.603      0.454      0.650     -85.331     136.779
temperature_106_max   -223.2883    185.058     -1.207      0.228    -586.369     139.792
temperature_110_max   -102.4233    209.167     -0.490      0.624    -512.805     307.958
co2_111_max             -2.2178      0.528     -4.198      0.000      -3.254      -1.181
light_111_max           -1.4991      0.601     -2.493      0.013      -2.679      -0.319
tvoc_112_max             0.0145      0.108      0.134      0.893      -0.197       0.226
weather_out_max         81.8436     68.827      1.189      0.235     -53.194     216.881
windows_max            439.8101    146.602      3.000      0.003     152.179     727.441
temperature_100_min     71.3243     91.121      0.783      0.434    -107.454     250.102
co2_102_min              0.0529      0.414      0.128      0.898      -0.760       0.866
tvoc_105_min            -0.0602      0.032     -1.853      0.064      -0.124       0.004
temperature_105_min   -143.7887    137.666     -1.044      0.296    -413.886     126.309
humidity_105_min        99.9363     57.438      1.740      0.082     -12.756     212.629
temperature_106_min      8.0640    174.518      0.046      0.963    -334.337     350.465
temperature_110_min     99.9507    228.941      0.437      0.662    -349.227     549.129
co2_111_min              0.2531      0.564      0.449      0.653      -0.853       1.359
light_111_min            1.7249      0.584      2.953      0.003       0.579       2.871
tvoc_112_min            -0.0070      0.111     -0.063      0.950      -0.224       0.210
weather_out_min       -235.4270     70.831     -3.324      0.001    -374.397     -96.457
windows_min           -652.1111    205.036     -3.180      0.002   -1054.389    -249.833
temperature_100_mean   -10.5753      2.378     -4.447      0.000     -15.242      -5.909
co2_102_mean            -2.8728      2.499     -1.149      0.251      -7.777       2.031
tvoc_105_mean           -3.9947      1.442     -2.769      0.006      -6.825      -1.165
temperature_105_mean    -1.7881      2.097     -0.852      0.394      -5.903       2.327
humidity_105_mean       -3.6411      0.790     -4.610      0.000      -5.191      -2.092
temperature_106_mean     4.4321      2.914      1.521      0.129      -1.285      10.149
temperature_110_mean    -0.0298      1.998     -0.015      0.988      -3.949       3.890
co2_111_mean            -2.9911      2.751     -1.087      0.277      -8.389       2.407
light_111_mean          -1.3730      2.297     -0.598      0.550      -5.880       3.134
tvoc_112_mean           -1.2009      0.722     -1.663      0.097      -2.618       0.216
weather_out_mean         3.9546      1.708      2.315      0.021       0.603       7.306
windows_mean             6.5710      2.767      2.375      0.018       1.142      12.000
temperature_100_std   -173.0723    176.466     -0.981      0.327    -519.295     173.151
co2_102_std              0.3040      1.002      0.303      0.762      -1.661       2.269
tvoc_105_std            -0.0979      0.075     -1.313      0.189      -0.244       0.048
temperature_105_std   -238.5926    336.480     -0.709      0.478    -898.761     421.576
humidity_105_std        93.9897    139.240      0.675      0.500    -179.196     367.176
temperature_106_std     45.5565    428.739      0.106      0.915    -795.622     886.735
temperature_110_std    246.6786    551.407      0.447      0.655    -835.172    1328.529
co2_111_std              3.4999      1.355      2.584      0.010       0.842       6.158
light_111_std            3.7958      1.389      2.733      0.006       1.071       6.521
tvoc_112_std            -0.0152      0.266     -0.057      0.954      -0.537       0.507
weather_out_std       -349.8953    159.421     -2.195      0.028    -662.676     -37.115
windows_std           -940.6462    344.043     -2.734      0.006   -1615.653    -265.639
temperature_100_sum    -62.3906     13.784     -4.526      0.000     -89.434     -35.347
co2_102_sum              0.5665      0.416      1.363      0.173      -0.249       1.382
tvoc_105_sum             0.6694      0.240      2.787      0.005       0.198       1.141
temperature_105_sum     -9.6345     12.736     -0.756      0.450     -34.622      15.353
humidity_105_sum       -20.8436      4.605     -4.526      0.000     -29.879     -11.809
temperature_106_sum     27.7175     17.032      1.627      0.104      -5.700      61.135
temperature_110_sum      0.5662     11.285      0.050      0.960     -21.576      22.708
co2_111_sum              0.8166      0.476      1.717      0.086      -0.116       1.750
light_111_sum            0.1863      0.386      0.483      0.629      -0.571       0.944
tvoc_112_sum             0.2043      0.120      1.700      0.089      -0.032       0.440
weather_out_sum         24.4246      9.928      2.460      0.014       4.946      43.903
windows_sum             39.4703     16.601      2.378      0.018       6.900      72.041
==============================================================================
Omnibus:                      589.376   Durbin-Watson:                   0.620
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5640.167
Skew:                           1.994   Prob(JB):                         0.00
Kurtosis:                      12.717   Cond. No.                     1.17e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.4e-21. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
estimator = SVR(kernel="linear")
selector = RFE(estimator, n_features_to_select=10, step=1)
selector = selector.fit(X, y)
selector.support_
selector.ranking_

In [ ]:
selector.ranking_

In [ ]:
plt.plot(y_train)
plt.show()

In [ ]:
# from sklearn.datasets import make_friedman1
# from sklearn.feature_selection import RFECV
# from sklearn.svm import SVR
# #X, y = make_friedman1(n_samples=50, n_features=10, random_state=0)
# estimator = SVR(kernel="linear")
# selector = RFECV(estimator, step=1, cv=5)
# selector = selector.fit(X1, y1)
# selector.support_

# selector.ranking_

In [ ]:
# from sklearn.datasets import make_friedman1
# from sklearn.feature_selection import RFE
# from sklearn.svm import SVR
# # X, y = make_friedman1(n_samples=50, n_features=10, random_state=0)
# estimator = SVR(kernel="linear")
# selectorRFE = RFE(estimator, n_features_to_select=10, step=1)
# selectorRFE = selectorRFE.fit(X_train, y_train)
# selectorRFE.support_
# selectorRFE.ranking_

In [ ]:
selectorRFE.feature_names_in_

In [ ]:
colonesSelected = []
for i,j in enumerate(selectorRFE.ranking_):
    # print(j)
    if j<5:
        colonesSelected.append(i)

In [ ]:
var=X_train.columns[colonesSelected]

In [ ]:
var

In [ ]:
var =['temperature_103', 'light_103', 'sound_103', 'temperature_104',
       'light_104', 'light_105', 'light_106', 'temperature_107', 'light_107',
       'tvoc_108', 'sound_108', 'temperature_110', 'temperature_112']

In [ ]:
import pandas
from sklearn import linear_model

X = X[var].copy()
print(X.columns)
col = [0, 4, 5, 7, 8, 9, 13, 14, 15, 17, 18, 21, 25, 26, 29, 30, 32, 33, 34, 35, 36]
col = [0, 4, 5, 7,  9, 13, 15, 18, 21, 26,  30]
col2    =[0, 1, 2, 3, 4, 5,6,  8, 10, 11, 13, 14,15]
# X= X[col]
#X= X.iloc[:,col]
y = y
# importing train_test_split from sklearn
from sklearn.model_selection import train_test_split
# splitting the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42, shuffle = False)

X_train = X_train.values
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
datascaler=scaler.fit(X_train)
X_train= datascaler.transform(X_train)
X_test= datascaler.transform(X_test)

regr = linear_model.LinearRegression()
regr.fit(X_train, y_train)
y_pred = regr.predict(X_test)


print(regr.coef_)

In [ ]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from scipy import stats

X2 = sm.add_constant(X_train)
est = sm.OLS(y_train, X2)
est2 = est.fit()
print(est2.summary())

In [ ]:
lm = linear_model.LinearRegression()
X, y=X_train, y_train
lm.fit(X,y)
params = np.append(lm.intercept_,lm.coef_)
predictions = lm.predict(X)

newX = pd.DataFrame({"Constant":np.ones(len(X))}).join(pd.DataFrame(X))
MSE = (sum((y-predictions)**2))/(len(newX)-len(newX.columns))

# Note if you don't want to use a DataFrame replace the two lines above with
# newX = np.append(np.ones((len(X),1)), X, axis=1)
# MSE = (sum((y-predictions)**2))/(len(newX)-len(newX[0]))

var_b = MSE*(np.linalg.inv(np.dot(newX.T,newX)).diagonal())
sd_b = np.sqrt(var_b)
ts_b = params/sd_b

p_values =[2*(1-stats.t.cdf(np.abs(i),(len(newX)-len(newX.columns)-1))) for i in ts_b]

sd_b = np.round(sd_b,3)
ts_b = np.round(ts_b,3)
p_values = np.round(p_values,3)
params = np.round(params,4)

myDF3 = pd.DataFrame()
myDF3["Coefficients"],myDF3["Standard Errors"],myDF3["t values"],myDF3["Probabilities"] = [params,sd_b,ts_b,p_values]
print(myDF3)

In [ ]:
col= []
for i,pval in enumerate(myDF3["Probabilities"]):
    if pval<=0.001:
        col.append(i-1)
col   = col[1:]

In [ ]:
col

In [ ]:
# importing r2_score module
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
# predicting the accuracy score
score=r2_score(y_test,y_pred)
print("r2 socre is ",score)
print("mean_sqrd_error is ",mean_squared_error(y_test,y_pred))
print("root_mean_squared error of is ",np.sqrt(mean_squared_error(y_test,y_pred)))

In [ ]:
d = {'y_pred': y_pred, 'y_test': y_test}
dfplot= pd.DataFrame(data=d)
dfplot.plot()

## Missing data generation

In [ ]:
#!pip install torch
#!pip install wget 
import wget
#wget.download('https://raw.githubusercontent.com/BorisMuzellec/MissingDataOT/master/utils.py')

import numpy as np
import pandas as pd
from utils import *
import torch
import seaborn as sns

In [ ]:
df1 = df.copy()

In [ ]:
df.plot()

In [ ]:
#!pip install category_encoders
import category_encoders as ce
# Get a new clean dataframe
obj_df = df1.select_dtypes(include=['object']).copy()

In [ ]:
df1 = obj_df.replace(x)

In [ ]:
df1.plot()

In [ ]:
# Fix the seed ------------------------------------------------------
np.random.seed(2)

In [ ]:
# Function produce_NA for generating missing values ------------------------------------------------------

def produce_NA(X, p_miss, mecha="MCAR", opt=None, p_obs=None, q=None):
    """
    Generate missing values for specifics missing-data mechanism and proportion of missing values. 
    
    Parameters
    ----------
    X : torch.DoubleTensor or np.ndarray, shape (n, d)
        Data for which missing values will be simulated.
        If a numpy array is provided, it will be converted to a pytorch tensor.
    p_miss : float
        Proportion of missing values to generate for variables which will have missing values.
    mecha : str, 
            Indicates the missing-data mechanism to be used. "MCAR" by default, "MAR", "MNAR" or "MNARsmask"
    opt: str, 
         For mecha = "MNAR", it indicates how the missing-data mechanism is generated: using a logistic regression ("logistic"), quantile censorship ("quantile") or logistic regression for generating a self-masked MNAR mechanism ("selfmasked").
    p_obs : float
            If mecha = "MAR", or mecha = "MNAR" with opt = "logistic" or "quanti", proportion of variables with *no* missing values that will be used for the logistic masking model.
    q : float
        If mecha = "MNAR" and opt = "quanti", quantile level at which the cuts should occur.
    
    Returns
    ----------
    A dictionnary containing:
    'X_init': the initial data matrix.
    'X_incomp': the data with the generated missing values.
    'mask': a matrix indexing the generated missing values.s
    """
    
    to_torch = torch.is_tensor(X) ## output a pytorch tensor, or a numpy array
    if not to_torch:
        X = X.astype(np.float32)
        X = torch.from_numpy(X)
    
    if mecha == "MAR":
        mask = MAR_mask(X, p_miss, p_obs).double()
    elif mecha == "MNAR" and opt == "logistic":
        mask = MNAR_mask_logistic(X, p_miss, p_obs).double()
    elif mecha == "MNAR" and opt == "quantile":
        mask = MNAR_mask_quantiles(X, p_miss, q, 1-p_obs).double()
    elif mecha == "MNAR" and opt == "selfmasked":
        mask = MNAR_self_mask_logistic(X, p_miss).double()
    else:
        mask = (torch.rand(X.shape) < p_miss).double()
    
    X_nas = X.clone()
    X_nas[mask.bool()] = np.nan
    
    return {'X_init': X.double(), 'X_incomp': X_nas.double(), 'mask': mask}

In [ ]:
X = df.copy()
shelly_219 =  ['state_AA7BF5','state_AA4706', 'state_AA9130', 'state_483FDA81E0F4']
for shelly in shelly_219:
    X = X.drop([shelly ], axis=1)

In [ ]:
X.columns

In [ ]:
X = X.values
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
datascaler=scaler.fit(X)
X= datascaler.transform(X)

In [ ]:
import pandas as pd
df= pd.DataFrame(X)
df.index=data.index

In [ ]:
df.head()

In [ ]:
#df.to_csv('dataComplet_219.csv')

## MCAR Generation

In [ ]:
# Minimal example for generating missing data ------------------------
p='5.csv'
X_miss_mcar = produce_NA(X, p_miss=0.05, mecha="MCAR")
X_mcar = X_miss_mcar['X_incomp']
R_mcar = X_miss_mcar['mask']

print("Percentage of newly generated missing values: ", (R_mcar.sum()).numpy()/np.prod(R_mcar.size())*100, " %")

df = X_mcar
df = df.numpy()
mask=R_mcar
mask = mask.numpy()

df = pd.DataFrame(data=df, columns=['Temperature', 'Humidity', 'CO2', 'Noise','Pressure'])
mask = pd.DataFrame(data=mask, columns=['Temperature', 'Humidity', 'CO2', 'Noise','Pressure'])

df['time']= data.index
df.set_index('time',inplace = True)
mask['time']= data.index
mask.set_index('time',inplace = True)
df.to_csv('MCAR'+p)
mask.to_csv('mask'+p)

In [ ]:
#df.to_csv('MCAR25.csv')
# supprimer d'abord les deux lignes dans le fichier d'export Neatatmo
index_col="time"
df=pd.read_csv('MCAR40.csv', sep=",", encoding = "ISO-8859-1", index_col=index_col)
mask=pd.read_csv('mask40.csv', sep=",", encoding = "ISO-8859-1", index_col=index_col)
mask=mask.values

In [ ]:
# Sample mar data -----------------------------------------
X_miss_mar = produce_NA(X, p_miss=0.4, mecha="MAR", p_obs=0.4)

X_mar = X_miss_mar['X_incomp']
R_mar = X_miss_mar['mask']

print("Percentage of generated missing values: ", (R_mar.sum()).numpy()/np.prod(R_mar.size())*100, " %")

ax = sns.heatmap(X_mar, mask=R_mar.numpy()==1, linewidths=0.02, linecolor='black')

df = X_mar
df = df.numpy()
mask_mar = R_mar
mask_mar = mask_mar.numpy()

df = pd.DataFrame(data=df, columns=['Temperature', 'Humidity', 'CO2', 'Noise','Pressure'])
mask_mar = pd.DataFrame(data=mask_mar, columns=['Temperature', 'Humidity', 'CO2', 'Noise','Pressure'])

In [ ]:
# df['time']= data.index
# df.set_index('time',inplace = True)
# mask_mar['time'] = data.index
# mask_mar.set_index('time',inplace = True)
# df.to_csv('MAR'+p)
# mask_mar.to_csv('mask_mar'+p)

In [ ]:
# Minimal example for generating missing data ------------------------
p='5.csv'

In [ ]:
pourcentage=5
p=